<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('cities')->delete();
        $states = array(

        	array('name' => "Al Khobar",'state_id' => 1),
			array('name' => "Aseer",'state_id' => 2),
			array('name' => "Ash Sharqiyah",'state_id' => 3),
			array('name' => "Asir",'state_id' => 4),
			array('name' => "Central Province",'state_id' => 5),
			array('name' => "Eastern Province",'state_id' => 6), 
			array('name' => "Ha'il",'state_id' => 7),
			array('name' => "Jawf",'state_id' => 8),
			array('name' => "Jizan",'state_id' => 9),
			array('name' => "Makkah",'state_id' => 10),
			array('name' => "Najran",'state_id' => 11),
			array('name' => "Qasim",'state_id' => 12),
			array('name' => "Tabuk",'state_id' => 13),
			array('name' => "Western Province",'state_id' => 14),
			array('name' => "al-Bahah",'state_id' => 15),
			array('name' => "al-Hudud-ash-Shamaliyah",'state_id' => 16),
			array('name' => "al-Madinah",'state_id' => 17),
			array('name' => "ar-Riyad",'state_id' => 18),
			array('name' => "Abu Zabi",'state_id' => 19),
			array('name' => "Ajman",'state_id' => 20),
			array('name' => "Dubai",'state_id' => 21),
			array('name' => "Ras al-Khaymah",'state_id' => 22),
			array('name' => "Sharjah",'state_id' => 23),
			array('name' => "Sharjha",'state_id' => 24),
			array('name' => "Umm al Qaywayn",'state_id' => 25),
			array('name' => "al-Fujayrah",'state_id' => 26),
			array('name' => "ash-Shariqah",'state_id' => 27),
			array('name' => "Al Buraimi",'state_id' => 28),
			array('name' => "Dhufar",'state_id' => 29),
			array('name' => "Masqat",'state_id' => 30),
			array('name' => "Musandam",'state_id' => 31),
			array('name' => "Rusayl",'state_id' => 32),
			array('name' => "Wadi Kabir",'state_id' => 33),
			array('name' => "ad-Dakhiliyah",'state_id' => 34),
			array('name' => "adh-Dhahirah",'state_id' => 35),
			array('name' => "al-Batinah",'state_id' => 36),
			array('name' => "ash-Sharqiyah",'state_id' => 37),
			array('name' => "Adan",'state_id' => 38),
			array('name' => "Abyan",'state_id' => 39),
			array('name' => "Dhamar",'state_id' => 40),
			array('name' => "Hadramaut",'state_id' => 41),
			array('name' => "Hajjah",'state_id' => 42),
			array('name' => "Hudaydah",'state_id' => 43),
			array('name' => "Ibb",'state_id' => 44),
			array('name' => "Lahij",'state_id' => 45),
			array('name' => "Ma'rib",'state_id' => 46),
			array('name' => "Madinat San'a",'state_id' => 47),
			array('name' => "Sa'dah",'state_id' => 48),
			array('name' => "Sana",'state_id' => 49),
			array('name' => "Shabwah",'state_id' => 50),
			array('name' => "Ta'izz",'state_id' => 51),
			array('name' => "al-Bayda",'state_id' => 52),
			array('name' => "al-Hudaydah",'state_id' => 53),
			array('name' => "al-Jawf",'state_id' => 54),
			array('name' => "al-Mahrah",'state_id' => 55),
			array('name' => "al-Mahwit",'state_id' => 56),
			array('name' => "Doha",'state_id' => 57),
			array('name' => "Jarian-al-Batnah",'state_id' => 58),
			array('name' => "Umm Salal",'state_id' => 59),
			array('name' => "ad-Dawhah",'state_id' => 60),
			array('name' => "al-Ghuwayriyah",'state_id' => 61),
			array('name' => "al-Jumayliyah",'state_id' => 62),
			array('name' => "al-Khawr",'state_id' => 63),
			array('name' => "al-Wakrah",'state_id' => 64),
			array('name' => "ar-Rayyan",'state_id' => 65),
			array('name' => "ash-Shamal",'state_id' => 66),
			array('name' => "'Isa",'state_id' => 67),
			array('name' => "Badiyah",'state_id' => 68),
			array('name' => "Hidd",'state_id' => 69),
			array('name' => "Jidd Hafs",'state_id' => 70),
			array('name' => "Mahama",'state_id' => 71),
			array('name' => "Manama",'state_id' => 72),
			array('name' => "Sitrah",'state_id' => 73),
			array('name' => "al-Manamah",'state_id' => 74),
			array('name' => "al-Muharraq",'state_id' => 75),
			array('name' => "ar-Rifa'a",'state_id' => 76),
			array('name' => "'Ajlun",'state_id' => 77),
			array('name' => "Amman",'state_id' => 78),
			array('name' => "Irbid",'state_id' => 79),
			array('name' => "Jarash",'state_id' => 80),
			array('name' => "Ma'an",'state_id' => 81),
			array('name' => "Madaba",'state_id' => 82),
			array('name' => "al-'Aqabah",'state_id' => 83),
			array('name' => "al-Balqa'",'state_id' => 84),
			array('name' => "al-Karak",'state_id' => 85),
			array('name' => "al-Mafraq",'state_id' => 86),
			array('name' => "at-Tafilah",'state_id' => 87),
			array('name' => "az-Zarqa'",'state_id' => 88),
			array('name' => "Beirut",'state_id' => 89),
			array('name' => "Jabal Lubnan",'state_id' => 90),
			array('name' => "Mohafazat Liban-Nord",'state_id' => 91),
			array('name' => "Mohafazat Mont-Liban",'state_id' => 92),
			array('name' => "Sidon",'state_id' => 93),
			array('name' => "al-Biqa",'state_id' => 94),
			array('name' => "al-Janub",'state_id' => 95),
			array('name' => "an-Nabatiyah",'state_id' => 96),
			array('name' => "ash-Shamal",'state_id' => 97),
			array('name' => "Ariha",'state_id' => 98),
			array('name' => "Bayt Lahm",'state_id' => 99),
			array('name' => "Bethlehem",'state_id' => 100),
			array('name' => "Dayr-al-Balah",'state_id' => 101),
			array('name' => "Ghazzah",'state_id' => 102),
			array('name' => "Ghazzah ash-Shamaliyah",'state_id' => 103),
			array('name' => "Janin",'state_id' => 104),
			array('name' => "Khan Yunis",'state_id' => 105),
			array('name' => "Nabulus",'state_id' => 106),
			array('name' => "Qalqilyah",'state_id' => 107),
			array('name' => "Rafah",'state_id' => 108),
			array('name' => "Ram Allah wal-Birah",'state_id' => 109),
			array('name' => "Salfit",'state_id' => 110),
			array('name' => "Tubas",'state_id' => 111),
			array('name' => "Tulkarm",'state_id' => 112),
			array('name' => "al-Khalil",'state_id' => 113),
			array('name' => "al-Quds",'state_id' => 114),
			array('name' => "Al Asimah",'state_id' => 115),
			array('name' => "Hawalli",'state_id' => 116),
			array('name' => "Mishref",'state_id' => 117),
			array('name' => "Qadesiya",'state_id' => 118),
			array('name' => "Safat",'state_id' => 119),
			array('name' => "Salmiya",'state_id' => 120),
			array('name' => "al-Ahmadi",'state_id' => 121),
			array('name' => "al-Farwaniyah",'state_id' => 122),
			array('name' => "al-Jahra",'state_id' => 123),
			array('name' => "al-Kuwayt",'state_id' => 124),
			array('name' => "Aryanah",'state_id' => 125),
			array('name' => "Bajah",'state_id' => 126),
			array('name' => "Bin 'Arus",'state_id' => 127),
			array('name' => "Binzart",'state_id' => 128),
			array('name' => "Gouvernorat de Ariana",'state_id' => 129),
			array('name' => "Gouvernorat de Nabeul",'state_id' => 130),
			array('name' => "Gouvernorat de Sousse",'state_id' => 131),
			array('name' => "Hammamet Yasmine",'state_id' => 132),
			array('name' => "Jundubah",'state_id' => 133),
			array('name' => "Madaniyin",'state_id' => 134),
			array('name' => "Manubah",'state_id' => 135),
			array('name' => "Monastir",'state_id' => 136),
			array('name' => "Nabul",'state_id' => 137),
			array('name' => "Qabis",'state_id' => 138),
			array('name' => "Qafsah",'state_id' => 139),
			array('name' => "Qibili",'state_id' => 140),
			array('name' => "Safaqis",'state_id' => 141),
			array('name' => "Sfax",'state_id' => 142),
			array('name' => "Sidi Bu Zayd",'state_id' => 143),
			array('name' => "Silyanah",'state_id' => 144),
			array('name' => "Susah",'state_id' => 145),
			array('name' => "Tatawin",'state_id' => 146),
			array('name' => "Tawzar",'state_id' => 147),
			array('name' => "Tunis",'state_id' => 148),
			array('name' => "Zaghwan",'state_id' => 149),
			array('name' => "al-Kaf",'state_id' => 150),
			array('name' => "al-Mahdiyah",'state_id' => 151),
			array('name' => "al-Munastir",'state_id' => 152),
			array('name' => "al-Qasrayn",'state_id' => 153),
			array('name' => "al-Qayrawan",'state_id' => 154),
			array('name' => "Ajdabiya",'state_id' => 155),
			array('name' => "Fezzan",'state_id' => 156),
			array('name' => "Banghazi",'state_id' => 157),
			array('name' => "Darnah",'state_id' => 158),
			array('name' => "Ghadamis",'state_id' => 159),
			array('name' => "Gharyan",'state_id' => 160),
			array('name' => "Misratah",'state_id' => 161),
			array('name' => "Murzuq",'state_id' => 162),
			array('name' => "Sabha",'state_id' => 163),
			array('name' => "Sawfajjin",'state_id' => 164),
			array('name' => "Surt",'state_id' => 165),
			array('name' => "Tarabulus",'state_id' => 166),
			array('name' => "Tarhunah",'state_id' => 167),
			array('name' => "Tripolitania",'state_id' => 168),
			array('name' => "Tubruq",'state_id' => 169),
			array('name' => "Yafran",'state_id' => 170),
			array('name' => "Zlitan",'state_id' => 171),
			array('name' => "al-'Aziziyah",'state_id' => 172),
			array('name' => "al-Fatih",'state_id' => 173),
			array('name' => "al-Jabal al Akhdar",'state_id' => 174),
			array('name' => "al-Jufrah",'state_id' => 175),
			array('name' => "al-Khums",'state_id' => 176),
			array('name' => "al-Kufrah",'state_id' => 177),
			array('name' => "an-Nuqat al-Khams",'state_id' => 178),
			array('name' => "ash-Shati'",'state_id' => 179),
			array('name' => "az-Zawiyah",'state_id' => 180),
			array('name' => "A'ali-an-Nil",'state_id' => 181),
			array('name' => "Bahr-al-Jabal",'state_id' => 182),
			array('name' => "Central Equatoria",'state_id' => 183),
			array('name' => "Gharb Bahr-al-Ghazal",'state_id' => 184),
			array('name' => "Gharb Darfur",'state_id' => 185),
			array('name' => "Gharb Kurdufan",'state_id' => 186),
			array('name' => "Gharb-al-Istiwa'iyah",'state_id' => 187),
			array('name' => "Janub Darfur",'state_id' => 188),
			array('name' => "Janub Kurdufan",'state_id' => 189),
			array('name' => "Junqali",'state_id' => 190),
			array('name' => "Kassala",'state_id' => 191),
			array('name' => "Nahr-an-Nil",'state_id' => 192),
			array('name' => "Shamal Bahr-al-Ghazal",'state_id' => 193),
			array('name' => "Shamal Darfur",'state_id' => 194),
			array('name' => "Shamal Kurdufan",'state_id' => 195),
			array('name' => "Sharq-al-Istiwa'iyah",'state_id' => 196),
			array('name' => "Sinnar",'state_id' => 197),
			array('name' => "Warab",'state_id' => 198),
			array('name' => "Wilayat al Khartum",'state_id' => 199),
			array('name' => "al-Bahr-al-Ahmar",'state_id' => 200),
			array('name' => "al-Buhayrat",'state_id' => 201),
			array('name' => "al-Jazirah",'state_id' => 202),
			array('name' => "al-Khartum",'state_id' => 203),
			array('name' => "al-Qadarif",'state_id' => 204),
			array('name' => "al-Wahdah",'state_id' => 205),
			array('name' => "an-Nil-al-Abyad",'state_id' => 206),
			array('name' => "an-Nil-al-Azraq",'state_id' => 207),
			array('name' => "ash-Shamaliyah",'state_id' => 208));

			DB::table('cities')->insert($states);

    }
}
