<?php

use Illuminate\Database\Seeder;

class StatesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('states')->delete();
        $states = array(
			array('name' => "Al Khobar",'country_id' => 1),
			array('name' => "Aseer",'country_id' => 1),
			array('name' => "Ash Sharqiyah",'country_id' => 1),
			array('name' => "Asir",'country_id' => 1),
			array('name' => "Central Province",'country_id' => 1),
			array('name' => "Eastern Province",'country_id' => 1), 
			array('name' => "Ha'il",'country_id' => 1),
			array('name' => "Jawf",'country_id' => 1),
			array('name' => "Jizan",'country_id' => 1),
			array('name' => "Makkah",'country_id' => 1),
			array('name' => "Najran",'country_id' => 1),
			array('name' => "Qasim",'country_id' => 1),
			array('name' => "Tabuk",'country_id' => 1),
			array('name' => "Western Province",'country_id' => 1),
			array('name' => "al-Bahah",'country_id' => 1),
			array('name' => "al-Hudud-ash-Shamaliyah",'country_id' => 1),
			array('name' => "al-Madinah",'country_id' => 1),
			array('name' => "ar-Riyad",'country_id' => 1),
			array('name' => "Abu Zabi",'country_id' => 2),
			array('name' => "Ajman",'country_id' => 2),
			array('name' => "Dubai",'country_id' => 2),
			array('name' => "Ras al-Khaymah",'country_id' => 2),
			array('name' => "Sharjah",'country_id' => 2),
			array('name' => "Sharjha",'country_id' => 2),
			array('name' => "Umm al Qaywayn",'country_id' => 2),
			array('name' => "al-Fujayrah",'country_id' => 2),
			array('name' => "ash-Shariqah",'country_id' => 2),
			array('name' => "Al Buraimi",'country_id' => 3),
			array('name' => "Dhufar",'country_id' => 3),
			array('name' => "Masqat",'country_id' => 3),
			array('name' => "Musandam",'country_id' => 3),
			array('name' => "Rusayl",'country_id' => 3),
			array('name' => "Wadi Kabir",'country_id' => 3),
			array('name' => "ad-Dakhiliyah",'country_id' => 3),
			array('name' => "adh-Dhahirah",'country_id' => 3),
			array('name' => "al-Batinah",'country_id' => 3),
			array('name' => "ash-Sharqiyah",'country_id' => 3),
			array('name' => "Adan",'country_id' => 4),
			array('name' => "Abyan",'country_id' => 4),
			array('name' => "Dhamar",'country_id' => 4),
			array('name' => "Hadramaut",'country_id' => 4),
			array('name' => "Hajjah",'country_id' => 4),
			array('name' => "Hudaydah",'country_id' => 4),
			array('name' => "Ibb",'country_id' => 4),
			array('name' => "Lahij",'country_id' => 4),
			array('name' => "Ma'rib",'country_id' => 4),
			array('name' => "Madinat San'a",'country_id' => 4),
			array('name' => "Sa'dah",'country_id' => 4),
			array('name' => "Sana",'country_id' => 4),
			array('name' => "Shabwah",'country_id' => 4),
			array('name' => "Ta'izz",'country_id' => 4),
			array('name' => "al-Bayda",'country_id' => 4),
			array('name' => "al-Hudaydah",'country_id' => 4),
			array('name' => "al-Jawf",'country_id' => 4),
			array('name' => "al-Mahrah",'country_id' => 4),
			array('name' => "al-Mahwit",'country_id' => 4),
			array('name' => "Doha",'country_id' => 5),
			array('name' => "Jarian-al-Batnah",'country_id' => 5),
			array('name' => "Umm Salal",'country_id' => 5),
			array('name' => "ad-Dawhah",'country_id' => 5),
			array('name' => "al-Ghuwayriyah",'country_id' => 5),
			array('name' => "al-Jumayliyah",'country_id' => 5),
			array('name' => "al-Khawr",'country_id' => 5),
			array('name' => "al-Wakrah",'country_id' => 5),
			array('name' => "ar-Rayyan",'country_id' => 5),
			array('name' => "ash-Shamal",'country_id' => 5),
			array('name' => "'Isa",'country_id' => 6),
			array('name' => "Badiyah",'country_id' => 6),
			array('name' => "Hidd",'country_id' => 6),
			array('name' => "Jidd Hafs",'country_id' => 6),
			array('name' => "Mahama",'country_id' => 6),
			array('name' => "Manama",'country_id' => 6),
			array('name' => "Sitrah",'country_id' => 6),
			array('name' => "al-Manamah",'country_id' => 6),
			array('name' => "al-Muharraq",'country_id' => 6),
			array('name' => "ar-Rifa'a",'country_id' => 6),
			array('name' => "'Ajlun",'country_id' => 7),
			array('name' => "Amman",'country_id' => 7),
			array('name' => "Irbid",'country_id' => 7),
			array('name' => "Jarash",'country_id' => 7),
			array('name' => "Ma'an",'country_id' => 7),
			array('name' => "Madaba",'country_id' => 7),
			array('name' => "al-'Aqabah",'country_id' => 7),
			array('name' => "al-Balqa'",'country_id' => 7),
			array('name' => "al-Karak",'country_id' => 7),
			array('name' => "al-Mafraq",'country_id' => 7),
			array('name' => "at-Tafilah",'country_id' => 7),
			array('name' => "az-Zarqa'",'country_id' => 7),
			array('name' => "Beirut",'country_id' => 8),
			array('name' => "Jabal Lubnan",'country_id' => 8),
			array('name' => "Mohafazat Liban-Nord",'country_id' => 8),
			array('name' => "Mohafazat Mont-Liban",'country_id' => 8),
			array('name' => "Sidon",'country_id' => 8),
			array('name' => "al-Biqa",'country_id' => 8),
			array('name' => "al-Janub",'country_id' => 8),
			array('name' => "an-Nabatiyah",'country_id' => 8),
			array('name' => "ash-Shamal",'country_id' => 8),
			array('name' => "Ariha",'country_id' => 9),
			array('name' => "Bayt Lahm",'country_id' => 9),
			array('name' => "Bethlehem",'country_id' => 9),
			array('name' => "Dayr-al-Balah",'country_id' => 9),
			array('name' => "Ghazzah",'country_id' => 9),
			array('name' => "Ghazzah ash-Shamaliyah",'country_id' => 9),
			array('name' => "Janin",'country_id' => 9),
			array('name' => "Khan Yunis",'country_id' => 9),
			array('name' => "Nabulus",'country_id' => 9),
			array('name' => "Qalqilyah",'country_id' => 9),
			array('name' => "Rafah",'country_id' => 9),
			array('name' => "Ram Allah wal-Birah",'country_id' => 9),
			array('name' => "Salfit",'country_id' => 9),
			array('name' => "Tubas",'country_id' => 9),
			array('name' => "Tulkarm",'country_id' => 9),
			array('name' => "al-Khalil",'country_id' => 9),
			array('name' => "al-Quds",'country_id' => 9),
			array('name' => "Al Asimah",'country_id' => 10),
			array('name' => "Hawalli",'country_id' => 10),
			array('name' => "Mishref",'country_id' => 10),
			array('name' => "Qadesiya",'country_id' => 10),
			array('name' => "Safat",'country_id' => 10),
			array('name' => "Salmiya",'country_id' => 10),
			array('name' => "al-Ahmadi",'country_id' => 10),
			array('name' => "al-Farwaniyah",'country_id' => 10),
			array('name' => "al-Jahra",'country_id' => 10),
			array('name' => "al-Kuwayt",'country_id' => 10),
			array('name' => "Aryanah",'country_id' => 11),
			array('name' => "Bajah",'country_id' => 11),
			array('name' => "Bin 'Arus",'country_id' => 11),
			array('name' => "Binzart",'country_id' => 11),
			array('name' => "Gouvernorat de Ariana",'country_id' => 11),
			array('name' => "Gouvernorat de Nabeul",'country_id' => 11),
			array('name' => "Gouvernorat de Sousse",'country_id' => 11),
			array('name' => "Hammamet Yasmine",'country_id' => 11),
			array('name' => "Jundubah",'country_id' => 11),
			array('name' => "Madaniyin",'country_id' => 11),
			array('name' => "Manubah",'country_id' => 11),
			array('name' => "Monastir",'country_id' => 11),
			array('name' => "Nabul",'country_id' => 11),
			array('name' => "Qabis",'country_id' => 11),
			array('name' => "Qafsah",'country_id' => 11),
			array('name' => "Qibili",'country_id' => 11),
			array('name' => "Safaqis",'country_id' => 11),
			array('name' => "Sfax",'country_id' => 11),
			array('name' => "Sidi Bu Zayd",'country_id' => 11),
			array('name' => "Silyanah",'country_id' => 11),
			array('name' => "Susah",'country_id' => 11),
			array('name' => "Tatawin",'country_id' => 11),
			array('name' => "Tawzar",'country_id' => 11),
			array('name' => "Tunis",'country_id' => 11),
			array('name' => "Zaghwan",'country_id' => 11),
			array('name' => "al-Kaf",'country_id' => 11),
			array('name' => "al-Mahdiyah",'country_id' => 11),
			array('name' => "al-Munastir",'country_id' => 11),
			array('name' => "al-Qasrayn",'country_id' => 11),
			array('name' => "al-Qayrawan",'country_id' => 11),
			array('name' => "Ajdabiya",'country_id' => 12),
			array('name' => "Fezzan",'country_id' => 12),
			array('name' => "Banghazi",'country_id' => 12),
			array('name' => "Darnah",'country_id' => 12),
			array('name' => "Ghadamis",'country_id' => 12),
			array('name' => "Gharyan",'country_id' => 12),
			array('name' => "Misratah",'country_id' => 12),
			array('name' => "Murzuq",'country_id' => 12),
			array('name' => "Sabha",'country_id' => 12),
			array('name' => "Sawfajjin",'country_id' => 12),
			array('name' => "Surt",'country_id' => 12),
			array('name' => "Tarabulus",'country_id' => 12),
			array('name' => "Tarhunah",'country_id' => 12),
			array('name' => "Tripolitania",'country_id' => 12),
			array('name' => "Tubruq",'country_id' => 12),
			array('name' => "Yafran",'country_id' => 12),
			array('name' => "Zlitan",'country_id' => 12),
			array('name' => "al-'Aziziyah",'country_id' => 12),
			array('name' => "al-Fatih",'country_id' => 12),
			array('name' => "al-Jabal al Akhdar",'country_id' => 12),
			array('name' => "al-Jufrah",'country_id' => 12),
			array('name' => "al-Khums",'country_id' => 12),
			array('name' => "al-Kufrah",'country_id' => 12),
			array('name' => "an-Nuqat al-Khams",'country_id' => 12),
			array('name' => "ash-Shati'",'country_id' => 12),
			array('name' => "az-Zawiyah",'country_id' => 12),
			array('name' => "A'ali-an-Nil",'country_id' => 13),
			array('name' => "Bahr-al-Jabal",'country_id' => 13),
			array('name' => "Central Equatoria",'country_id' => 13),
			array('name' => "Gharb Bahr-al-Ghazal",'country_id' => 13),
			array('name' => "Gharb Darfur",'country_id' => 13),
			array('name' => "Gharb Kurdufan",'country_id' => 13),
			array('name' => "Gharb-al-Istiwa'iyah",'country_id' => 13),
			array('name' => "Janub Darfur",'country_id' => 13),
			array('name' => "Janub Kurdufan",'country_id' => 13),
			array('name' => "Junqali",'country_id' => 13),
			array('name' => "Kassala",'country_id' => 13),
			array('name' => "Nahr-an-Nil",'country_id' => 13),
			array('name' => "Shamal Bahr-al-Ghazal",'country_id' => 13),
			array('name' => "Shamal Darfur",'country_id' => 13),
			array('name' => "Shamal Kurdufan",'country_id' => 13),
			array('name' => "Sharq-al-Istiwa'iyah",'country_id' => 13),
			array('name' => "Sinnar",'country_id' => 13),
			array('name' => "Warab",'country_id' => 13),
			array('name' => "Wilayat al Khartum",'country_id' => 13),
			array('name' => "al-Bahr-al-Ahmar",'country_id' => 13),
			array('name' => "al-Buhayrat",'country_id' => 13),
			array('name' => "al-Jazirah",'country_id' => 13),
			array('name' => "al-Khartum",'country_id' => 13),
			array('name' => "al-Qadarif",'country_id' => 13),
			array('name' => "al-Wahdah",'country_id' => 13),
			array('name' => "an-Nil-al-Abyad",'country_id' => 13),
			array('name' => "an-Nil-al-Azraq",'country_id' => 13),
			array('name' => "ash-Shamaliyah",'country_id' => 13)
		);

		DB::table('states')->insert($states);


    }
}
